export interface DonorTier {
  id: string;
  name: string;
  minimum: string;
  accentClass: string;
  donors: string[];
}

export const donorTiers: DonorTier[] = [
  {
    id: "gold",
    name: "Gold Supporter",
    minimum: "Below $50",
    accentClass: "text-yellow-600 dark:text-yellow-400",
    donors: [
      "A Robert Jacques",
      "Adam Levin",
      "Alex Hubbard",
      "Alexandria Burns",
      "Alfredo DeLeon",
      "Amanda Blurton",
      "Andrew Blevins",
      "Andy Hille",
      "Bradley Hoffman",
      "Brandi Besalke",
      "Brianna Gaskin",
      "Brian Cheli",
      "Brian Spath",
      "Carlos Vazquez",
      "Celina Tackett",
      "Charles Besalke",
      "Christie Hart",
      "Claire Akin",
      "Dana Lewis",
      "Danielle M King",
      "Danielle Pauly",
      "Darren Savage",
      "Davis Rigg",
      "Devin Belvin",
      "Emmett Shear",
      "Eric Kappel",
      "Faming Xu",
      "Ian Price",
      "Jef Albach",
      "Jessie Hautly",
      "Jodi Sankovitch",
      "John Rolfes",
      "Jonathan Laufer",
      "Julie McAlister",
      "Kate Ealey",
      "lauren cronk",
      "Laura Shoemaker",
      "Lauren Powers",
      "Matthew Jay",
      "Mike Esswein",
      "Miranda Dowden",
      "min liu",
      "Nathan Hunter",
      "Nicholas Clemens",
      "Quinn Jines",
      "Rachel Hill",
      "Rodolfo Keesey",
      "Ryan Chiu",
      "Salvatore Gianino",
      "Shana Ziolko",
      "Victor Yamaykin",
      "William He",
      "Zachary Voyer",
    ],
  },
  {
    id: "platinum",
    name: "Platinum Supporter",
    minimum: "$50+",
    accentClass: "text-cyan-700 dark:text-cyan-300",
    donors: [
      "Bruce Ward",
      "Jane Steible",
      "Jiayu Lin",
      "Michael Pate",
      "RANDAL WEISSENBORN",
      "Tim Snyder",
    ],
  },
  {
    id: "emerald",
    name: "Emerald Supporter",
    minimum: "$100+",
    accentClass: "text-emerald-700 dark:text-emerald-400",
    donors: ["Gwen Middeke", "Meghan Yankowskas"],
  },
  {
    id: "diamond",
    name: "Diamond Supporter",
    minimum: "$500+",
    accentClass: "text-indigo-700 dark:text-indigo-400",
    donors: ["Jeremy Johnson"],
  },
  {
    id: "master",
    name: "Master Supporter",
    minimum: "$1,000+",
    accentClass: "text-purple-700 dark:text-purple-400",
    donors: [],
  },
  {
    id: "grandmaster",
    name: "Grandmaster Supporter",
    minimum: "$2,500+",
    accentClass: "text-fuchsia-700 dark:text-fuchsia-400",
    donors: [],
  },
  {
    id: "challenger-circle",
    name: "Challenger Circle",
    minimum: "$3,000+",
    accentClass: "text-rose-700 dark:text-rose-400",
    donors: [],
  },
];
