export interface DonorTier {
  id: string;
  name: string;
  minimum: string;
  accentClass: string;
  donors: string[];
}

export const donorTiers: DonorTier[] = [
  {
    id: "gold",
    name: "Gold Supportor",
    minimum: "Below $50",
    accentClass: "text-yellow-600 dark:text-yellow-400",
    donors: [
      "Alex Hubbard",
      "Zachary Voyer",
      "A Robert Jacques",
      "Alfredo DeLeon",
      "Brianna Gaskin",
      "Shana Ziolko",
      "Brenden Lauer",
      "Andrew Blevins",
      "Faming Xu",
      "Ian Price",
      "Bradley Meisner",
      "Adam Levin",
      "lauren cronk",
      "min liu",
      "Jonathan Hart",
      "Devin Belvin",
      "Lauren Powers",
      "Salvatore Gianino",
      "Rodolfo Keesey",
      "Matthew Jay",
      "Christie Hart",
      "Brian Spath",
      "William He",
      "Brian Cheli",
      "Laura Shoemaker",
      "John Rolfes",
      "Andy Hille",
      "Davis Rigg",
      "Nicholas Clemens",
      "Bradley Hoffman",
      "Erin Higgs",
      "Danielle M King",
      "Dana Lewis",
      "Amanda Blurton",
      "KC Rivera",
      "Charles Besalke",
      "Brandi Besalke",
      "Alexandria Burns",
      "Christopher Hall",
      "Carlos Vazquez",
    ],
  },
  {
    id: "platinum",
    name: "Platinum Supportor",
    minimum: "$50+",
    accentClass: "text-cyan-700 dark:text-cyan-300",
    donors: ["Jane Steible", "Bruce Ward", "Jiayu Lin"],
  },
  {
    id: "emerald",
    name: "Emerald Supportor",
    minimum: "$100+",
    accentClass: "text-emerald-700 dark:text-emerald-400",
    donors: ["Gwen Middeke"],
  },
  {
    id: "diamond",
    name: "Diamond Supportor",
    minimum: "$500+",
    accentClass: "text-indigo-700 dark:text-indigo-400",
    donors: ["Jeremy Johnson"],
  },
  {
    id: "master",
    name: "Master Supportor",
    minimum: "$1,000+",
    accentClass: "text-purple-700 dark:text-purple-400",
    donors: [],
  },
  {
    id: "grandmaster",
    name: "Grandmaster Supportor",
    minimum: "$2,500+",
    accentClass: "text-fuchsia-700 dark:text-fuchsia-400",
    donors: [],
  },
  {
    id: "challenger-circle",
    name: "Challenger Circle",
    minimum: "$3,000+",
    accentClass: "text-rose-700 dark:text-rose-400",
    donors: [],
  },
];
